[APMON-406] Set Datadog namespace env variable on Cluster Agent
DataDog/datadog-operator pull request #1012
Opened 2023-12-08 17:35 UTC by liliyadd

### What does this PR do?

Sets an environment variable DD_KUBE_RESOURCES_NAMESPACE on Cluster Agent, indicating the Kubernetes namespace where Datadog is running at. This env variable is already set by Helm Charts and is used in Cluster Agent.

### Motivation

To move APM Instrumentation namespaces exclusion logic to Cluster Agent, Cluster Agent needs to know the namespace where it's running.

### Additional Notes

Anything else we should know when reviewing?

### Minimum Agent Versions

Are there minimum versions of the Datadog Agent and/or Cluster Agent required?

* Agent: vX.Y.Z
* Cluster Agent: vX.Y.Z

### Describe your test plan

Updated Cluster Agent unit-tests in the Operator

### Checklist

- [x] PR has at least one valid label: `bug`, `enhancement`, `refactoring`, `documentation`, `tooling`, and/or `dependencies`
- [x] PR has a milestone or the `qa/skip-qa` label

2023-12-12 19:44 UTC, khewonc requested changes

2023-12-12 19:44 UTC, khewonc commented on controllers/datadogagent/clusteragent.go
> +		},
Hi, this file configures the cluster agent for the old controller of the operator that we're trying to move away from in favor of the newer version that was GA'ed in v1.0.0. Could you instead make the change for the newer operator version? Adding the env var under `defaultEnvVars` in [this file](https://github.com/DataDog/datadog-operator/blob/7bd890e16e83176f5cd085e39e624d040172fd45/controllers/datadogagent/component/clusteragent/default.go#L121) instead should make the equivalent change.

2023-12-13 16:28 UTC, Julia-elsammak commented
Hi Team. I will be working on implementing changes for the newer operator version: 
> Adding the env var under `defaultEnvVars` (https://github.com/DataDog/datadog-operator/blob/7bd890e16e83176f5cd085e39e624d040172fd45/controllers/datadogagent/component/clusteragent/default.go#L121)

2023-12-15 17:20 UTC, celenechang commented on controllers/datadogagent/clusteragent_test.go
> +		},
this can be removed as well

2023-12-18 15:46 UTC, liliyadd commented
@khewonc can you please re-review this PR now that @Julia-elsammak moved setting the new env variable into a new controller?

2023-12-18 19:10 UTC, khewonc approved these changes

2023-12-18 19:26 UTC, merged