Update getting started guide links to helm charts
DataDog/datadog-operator pull request #206
Opened 2021-01-14 17:24 UTC by maxgio92

### What does this PR do?

Fixes links to Helm chart in the Getting started documentation.

### Motivation

The links to Helm charts were broken.

2021-01-14 20:04 UTC, ruthnaebeck requested changes
Docs review

2021-01-14 20:04 UTC, ruthnaebeck commented on docs/getting_started.md
>  ## Deploy an agent with the operator
```suggestion
## Deploy the Agent with the operator
```

2021-01-14 20:04 UTC, ruthnaebeck commented on docs/getting_started.md
> +In order to deploy a Datadog agent with the operator in the minimum number of steps, the [`datadog-operator`](https://github.com/DataDog/helm-charts/tree/master/charts/datadog-operator) helm chart ca
```suggestion
To deploy the Datadog Agent with the operator in the minimum number of steps, see the [`datadog-operator`](https://github.com/DataDog/helm-charts/tree/master/charts/datadog-operator) helm chart.
```

2021-01-26 18:55 UTC, maxgio92 commented
> Docs review

Thank you. Applied.

2021-01-28 08:42 UTC, clamoriniere approved these changes

2021-01-28 08:42 UTC, merged