Add support for Cilium network policies
DataDog/datadog-operator pull request #363
Opened 2021-08-23 13:29 UTC by juliogreff

### What does this PR do?

Initially introduced in the helm chart:
https://github.com/DataDog/helm-charts/pull/99/ -- this PR adds the same
policies and also includes a couple of fixes introduced by
https://github.com/DataDog/helm-charts/pull/245.

### Describe your test plan

Enable the cilium network policies for the agent, check that they are created correctly, and that agent, cluster agent, and cluster checks runners still work as expected, look out for networking errors in particular.

2021-08-30 12:42 UTC, kayayarai requested changes

2021-08-30 12:42 UTC, kayayarai commented on docs/configuration.md
> +| agent.networkPolicy.flavor | Flavor of the network policy to use. Can be `kubernetes` or `cilium`. |
```suggestion
| agent.networkPolicy.flavor | Which network policy to use. Can be `kubernetes` or `cilium`. |
```

2021-08-30 12:42 UTC, kayayarai commented on docs/configuration.md
> +| agent.networkPolicy.dnsSelectorEndpoints |  |
Needs a description.

2021-08-30 12:42 UTC, kayayarai commented on docs/configuration.md
> +| clusterAgent.networkPolicy.flavor | Flavor of the network policy to use. Can be `kubernetes` or `cilium`. |
Same comments as above

2021-08-30 12:42 UTC, kayayarai commented on docs/configuration.md
> +| clusterChecksRunner.networkPolicy.flavor | Flavor of the network policy to use. Can be `kubernetes` or `cilium`. |
same comments as above.

2021-09-22 15:44 UTC, L3n41c commented on controllers/datadogagent/agent.go
> +		},
We might need to retrofit here DataDog/helm-charts#391 and to add
```yaml
ToEntities: []cilium.Entity{
	cilium.EntityHost,
},
```
to fix DataDog/helm-charts#387 also with the operator.

2021-09-27 15:00 UTC, kayayarai approved these changes

2021-11-26 15:55 UTC, clamoriniere reviewed
few comments
btw, I like the `builder` pattern 👍

2021-11-29 11:20 UTC, juliogreff commented on pkg/cilium/types.go
> +package cilium
Updated 👍

2021-11-30 08:58 UTC, clamoriniere approved these changes
Nice work 👍 

Do you have any test tips to enable cilium in a k8s cluster (kind, minikube? ) that can be added in the PR description?

2021-11-30 09:01 UTC, merged