doc: how to configure API/APP key with OLM
DataDog/datadog-operator pull request #427
Opened 2022-01-18 09:48 UTC by clamoriniere

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details you may have to test your PR.

2022-01-18 11:14 UTC, clamoriniere commented on docs/installation.md
> +  sourceNamespace: olm
```suggestion
  # ...
```

2022-01-18 14:34 UTC, davidor commented on docs/installation.md
> +            key: api-ky
`app-key`

2022-01-18 19:16 UTC, alai97 requested changes

2022-01-18 19:16 UTC, alai97 commented on docs/installation.md
>  ## Deploy the Datadog Agents with the operator
```suggestion
## Deploy the Datadog Agents with the Operator
```

2022-01-18 19:16 UTC, alai97 commented on docs/installation.md
> +            key: api-ky
Good catch!

```suggestion
            key: app-key
```

2022-01-18 19:16 UTC, alai97 commented on docs/installation.md
> +Create a secret that contains this two keys. In the following example the secret keys are `api-key` and `app-key`.
```suggestion
The Datadog Operator requires access to your API and application keys to add a `DatadogMonitor`. 

1. Create a secret that contains both keys. In the example below, the secret keys are `api-key` and `app-key`.
```

2022-01-18 19:16 UTC, alai97 commented on docs/installation.md
> +Add the references to the secret in the Datadog-Operator Subscription resource instance.
```suggestion
2. Add references to the secret in the Datadog-Operator Subscription resource instance. 
```

2022-01-18 19:16 UTC, alai97 commented on docs/installation.md
> +**Note**: several config overrides can be added on the `spec.config` section; example: `env` + `resources`
```suggestion
**Note**: You can add configuration overrides in the `spec.config` section. For example, override `env` and `resources`.
```

2022-01-24 17:48 UTC, clamoriniere commented
hi @davidor and @alai97,
I have updated the PR according to your suggestions. It is ready for a second review :)

2022-01-24 18:03 UTC, alai97 approved these changes

2022-01-24 20:21 UTC, merged