update metrics forwarder to support v2
DataDog/datadog-operator pull request #601
Opened 2022-08-23 21:08 UTC by celenechang

### What does this PR do?

Update Metrics Forwarder to support v2 as well as maintain support for v1 DatadogAgent.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Deploy the operator with the v1 DatadogAgent CRD enabled and set flag `operatorMetricsEnabled=true` . Apply the DatadogAgent, for instance `examples/datadogagent/datadog-agent-all.yaml`. Make sure that operator metrics are reporting to Datadog.

Do the same with the v2 CRD, using `examples/v2alpha1/min.yaml`.

2022-08-24 23:15 UTC, buraizu requested changes

2022-08-24 23:15 UTC, buraizu commented on docs/how-to-contribute.md
> +`system` namespace and only watches resources in the this namespace. As a result, the secret and deployment need to be done in the same namespace.
```suggestion
`system` namespace, and only watches resources in this namespace. As a result, the secret and deployment must be within the same namespace.
```

2022-08-31 10:11 UTC, clamoriniere reviewed
the PR looks good. 
small comment about struct decription

2022-08-31 10:11 UTC, clamoriniere commented on apis/datadoghq/common/v1/agent_types.go
> +	// Status corresponds to the ClusterAgent deployment computed status.
DeploymentStatus can be use also for the clustercheckrunner so it can be good to remove the notion of ClusterAgent in the description

2022-08-31 15:57 UTC, clamoriniere approved these changes
💯

2022-08-31 16:03 UTC, buraizu requested changes

2022-08-31 16:03 UTC, buraizu commented on docs/how-to-contribute.md
> +Then apply the `examples/v2alpha1/min.yaml` file which contains the mininum information needed to deploy the agent and related services.
```suggestion
Then apply the `examples/v2alpha1/min.yaml` file which contains the mininum information needed to deploy the Agent and related services.
```

2022-08-31 16:05 UTC, buraizu approved these changes

2022-08-31 16:23 UTC, merged