Add(doc): custom operator image
DataDog/datadog-operator pull request #875
Opened 2023-08-01 10:02 UTC by clamoriniere

### What does this PR do?

Add instruction to create a custom container image with a CA certificat

### Motivation

document user support case request

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details you may have to test your PR.

2023-08-01 22:11 UTC, rtrieu requested changes
Some changes requested before approving!

2023-08-01 22:11 UTC, rtrieu commented on docs/custom-operator-image.md
> +In some case, building a customer Operator image is needed, for example: to add a customer secret backend implementation, or to add CA certificat.
Can you provide some more context about what a custom operator image is and explain how it's used in Datadog? This sentence jumps right into "In some cases..." but it's not clear what a user might be doing at the time they'll need to build a customer operator image.

2023-08-01 22:11 UTC, rtrieu commented on docs/installation.md
> +### with the helm chart
```suggestion
### Datadog Operator images with Helm charts

To use a Datadog operator image with a Helm chart:

```

2023-08-01 22:11 UTC, rtrieu commented on docs/installation.md
> +you can find the instruction to build a Datadog Operator custom container image based on an official release [custom-operator-image.md][9]
```suggestion
See instructions to build a Datadog Operator custom container image on an official release in [Custom Operator container images][9].
```

2023-08-01 22:11 UTC, rtrieu commented on docs/custom-operator-image.md
> +# Customer Operator container image
```suggestion
# Customer Operator container images
```

2023-08-01 22:11 UTC, rtrieu commented on docs/custom-operator-image.md
> +In some case, building a customer Operator image is needed, for example: to add a customer secret backend implementation, or to add CA certificat.
```suggestion
When adding a customer secret backend implementation or adding a CA certificate, for example, you may need to build a customer Operator image.
```

2023-08-01 22:11 UTC, rtrieu commented on docs/custom-operator-image.md
> +## Add a CA certificat
```suggestion
## Add a Certificate Authority (CA) certificate
```

2023-08-01 22:11 UTC, rtrieu commented on docs/custom-operator-image.md
> +# Customer Operator container image
Just double checking - do you mean "Customer Operator container images" here or "Custom Operator container images"?

2023-08-03 11:06 UTC, celenechang commented on docs/custom-operator-image.md
> +# Customer Operator container images
```suggestion
# Custom Operator container images
```

2023-08-03 11:06 UTC, celenechang commented on docs/custom-operator-image.md
> +When adding a customer secret backend implementation or adding a CA certificate, for example, you may need to build a customer Operator image.
```suggestion
When adding a custom secret backend implementation or adding a CA certificate, for example, you may need to build a custom Operator image.
```

2023-08-03 11:07 UTC, celenechang commented on docs/installation.md
> +See instructions to build a Datadog Operator custom container image on an official release in [Custom Operator container images][9].
```suggestion
See instructions to build a Datadog Operator custom container image based on an official release in [Custom Operator container images][9].
```

2023-08-03 11:09 UTC, celenechang commented on docs/installation.md
> +To use a Datadog operator image with a Helm chart:
```suggestion
To install a custom Datadog Operator image using the Helm chart, run the following:
```

2023-08-08 12:21 UTC, celenechang commented on docs/custom-operator-image.md
> +## Run trust list to check that the certificat was properly added
```suggestion
## Run trust list to check that the certificate was properly added
```

2023-09-08 19:24 UTC, celenechang approved these changes

2023-09-11 16:31 UTC, merged