update openshift install docs and example
DataDog/datadog-operator pull request #884
Opened 2023-08-03 15:05 UTC by celenechang

### What does this PR do?

Clarify Operator install docs in Openshift

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Minimum Agent Versions

n/a

### Describe your test plan

Write there any instructions and details you may have to test your PR.

### Checklist

- [X] PR has at least one valid label: `bug`, `enhancement`, `refactoring`, `documentation`, `tooling`, and/or `dependencies`
- [X] PR has a milestone or the `qa/skip-qa` label

2023-08-03 19:50 UTC, drichards-87 requested changes
Left you some minor style-related feedback from the Docs Team.

2023-08-03 19:50 UTC, drichards-87 commented on docs/install-openshift.md
> +**Note**: Prior to version 1.0, multiple `InstallModes` were supported in the `ClusterServiceVersion` (see the [OLM operator install doc][3] as a reference). Due to the introduction of the conversion
```suggestion
**Note**: Prior to version 1.0, multiple `InstallModes` were supported in the `ClusterServiceVersion` (see the [OLM operator install doc][3] as a reference). Due to the introduction of the conversion webhook in 1.0, only the `AllNamespaces` `InstallMode` [is supported][4] in versions later than 1.0.
```

2023-08-03 19:50 UTC, drichards-87 commented on docs/install-openshift.md
> +The Datadog Agent and Cluster Agent should now be running and collecting data to be viewed and alerted on in the Datadog web app.
```suggestion
The Datadog Agent and Cluster Agent should now be running and collecting data. This data can be viewed and alerted on in Datadog.
```

2023-08-03 19:50 UTC, drichards-87 commented on docs/install-openshift.md
> +   Replace `<DATADOG_API_KEY>` and `<DATADOG_APP_KEY>` with your [Datadog API][5] and [Application keys][6]
```suggestion
   Replace `<DATADOG_API_KEY>` and `<DATADOG_APP_KEY>` with your [Datadog API][5] and [Application keys][6].
```

2023-08-03 19:50 UTC, drichards-87 commented on docs/install-openshift.md
> +After deploying the Datadog Operator, create a `DatadogAgent` resource that triggers a deployment of the Datadog Agent in your OpenShift cluster. The Agent is deployed as a `Daemonset`. It is recomme
```suggestion
After deploying the Datadog Operator, create a `DatadogAgent` resource that triggers a deployment of the Datadog Agent in your OpenShift cluster. The Agent is deployed as a `Daemonset`. Datadog recommends that you use the Cluster Agent to manage cluster-level monitoring, which will automatically be deployed by default.
```

2023-08-03 19:50 UTC, drichards-87 commented on docs/install-openshift.md
> +**Note**: In Datadog Operator versions `1.1.0` and above, the Conversion Webhook is **disabled** by default, and can be enabled with the command argument `--webhookEnabled`. In version `1.0.3` of the
```suggestion
**Notes**: 
- In Datadog Operator versions `1.1.0` and later, the conversion webhook is **disabled** by default. To enable the webhook, use the command argument `--webhookEnabled`. 
- In Datadog Operator version `1.0.3`, the conversion webhook is **enabled** by default. The conversion allows a smooth transition from the `v1alpha1` (deprecated) `DatadogAgent` CRD to `v2alpha1`.
```

2023-08-04 07:49 UTC, clamoriniere commented on examples/datadogagent/v2alpha1/datadog-agent-openshift.yaml
> +      replicas: 2
```suggestion
      replicas: 2

```

2023-08-04 07:50 UTC, clamoriniere commented on examples/datadogagent/v2alpha1/datadog-agent-openshift.yaml
> +      tlsVerify: false
is it mandatory?

2023-08-04 14:11 UTC, celenechang commented on docs/install-openshift.md
> +- In Datadog Operator versions `1.1.0` and later, the conversion webhook is **disabled** by default. To enable the webhook, use the command argument `--webhookEnabled`.
```suggestion
- In Datadog Operator versions `1.1` and later, the conversion webhook is **disabled** by default. To enable the webhook, use the command argument `--webhookEnabled`.
```

2023-08-04 14:39 UTC, drichards-87 approved these changes

2023-08-07 14:47 UTC, clamoriniere commented on examples/datadogagent/v2alpha1/datadog-agent-openshift.yaml
> +      tlsVerify: false
I think another solution is to mount the openshift root certificate

2023-08-07 14:49 UTC, clamoriniere commented on examples/datadogagent/v2alpha1/datadog-agent-openshift.yaml
> +      tlsVerify: false
can we add a comment to say that `tlsVerify: false` is needed of the kubelet certificate is a self-signed certificat. 

and another way is to mount the CA certificat that was used to create the kubelet certificate.

2023-08-07 14:52 UTC, fanny-jiang approved these changes

2023-08-11 12:33 UTC, merged